### ISSUE TITLE
If the game starts with no moves possible, this is not detected

### ISSUE THREAD

**Issue by pimveldhuisen** [asgill/SEM-25#9]
Should be pretty rare, but still

**Comment by jangerritharms** [comment]
In the start() function of the BejeweledGame class the function checkBoardCombos() is called which also invokes the outOfMoves() function. So I think it should be detected alright. Also the observer is added before the call to checkBoardCombos. I think it works or did you actually encounter that case?

**Comment by pimveldhuisen** [comment]
I actually ran in to this trying to test the function. If you replace in BoardFactory.java
this line:

 Jewel jewel = new Jewel(rand.nextInt((7 - 1) + 1) + 1, i, j);

with:

 Jewel jewel = new Jewel((i+j)%7+1, i, j);

to generate a board according to a pattern instead of randomly, you can actually see it. The board generates, but does not finish immediately. If you make two moves to come back to the same situation it finishes fine.
